const StaticImages: {[id: string]: any} = {
  'gripsholmstone178': require('./images/gripsholmstone178.jpg'),
  'gripsholmstone179': require('./images/gripsholmstone179.jpg'),
  'kylverstone': require('./images/kylverstone.jpg'),
  'lidingö_dalängen': require('./images/lidingö_dalängen.jpg'),
  'lidingö_askrikevägen': require('./images/lidingö_askrikevägen.jpg'),
  'bjärby_runsten': require('./images/bjärby_runsten.jpg'),
  'gårdby_runsten': require('./images/gårdby_runsten.jpg'),
  'picture_stone_stånga': require('./images/picture_stone_stånga.jpg'),
  'u614': require('./images/u614.jpg'),
  'rökstone_side_a': require('./images/rökstenen_side_a.jpg'),
  'sigurdristingen': require('./images/sigurdristingen.jpg'),
  'jellingstoneharald': require('./images/jellingstoneharald.png'),
  'kjølevikstone': require('./images/kjølevikstone.jpg'),
  'svingerudsteinen': require('./images/svingerudsteinen.jpg'),
  'eidi_runestick': require('./images/eidi_runestick.jpg'),
  'sandavagur_stone': require('./images/sandavagur_stone.jpg'),
  'sørvágur_box': require('./images/sørvágur_box.jpg'),
  'einang': require('./images/einangstone.jpg'),
  'bryggengohome': require('./images/bergenstick_gohome.jpg'),
  'grumpanbracteate': require('./images/grumpanbracteate.jpg'),
  'burserydfont': require('./images/burserydfont.jpg'),
  'maugholdstone': require('./images/maugholdstone.jpg'),
  'ågedalbracteate': require('./images/ågedalbracteate.jpg'),
  'codexrunicus': require('./images/codexrunicus.jpg'),
  'acvalhalla': require('./images/acvalhalla.jpg'),
  'adventure_time_guitar_repair': require('./images/at_guitar_repair.jpg'),
  'adventure_time_pitcher': require('./images/at_pitcher.jpg'),
  'adventure_time_sword_web_weirdos': require('./images/at_sword_web_weirdos.jpg'),
  'adventure_time_staff_storytelling': require('./images/at_staff_storytelling.jpg'),
  'adventure_time_sword_morituri': require('./images/at_sword_morituri.jpg'),
  'oseberg_oar': require('./images/oseberg_oar.jpg'),
}

export default StaticImages;